#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

LEADER_EXTERNS();
void matrix_scan_user(void) {
  LEADER_DICTIONARY() {
    leading = false;
    leader_end();
    // Replace the sequences below with your own sequences.
    SEQ_ONE_KEY(KC_T) {
      // When I press KC_LEAD and then T, this sends CTRL + SHIFT + T
      SEND_STRING(SS_LCTRL(SS_LSFT("t")));
    }
    SEQ_ONE_KEY(KC_A) {
      // When I press KC_LEAD and then T, this sends CTRL + SHIFT + T
      SEND_STRING(SS_LGUI(SS_LSFT("a")));
    }
    SEQ_ONE_KEY(KC_H) {
      // When I press KC_LEAD and then T, this sends CTRL + SHIFT + T
      SEND_STRING(SS_LCTRL(SS_LALT("h")));
    }
    SEQ_ONE_KEY(KC_D) {
      // When I press KC_LEAD and then T, this sends CTRL + SHIFT + T
      SEND_STRING(SS_LGUI("d"));
    }

    // Note: This is not an array, you don't need to put any commas
    // or semicolons between sequences.
    SEQ_TWO_KEYS(KC_N, KC_T) {
      // When I press KC_LEAD and then N followed by T, this sends CTRL + T
      SEND_STRING(SS_LCTRL("t"));
    }
  }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x5_2(

            KC_Q, KC_W, KC_E, KC_R, KC_T,  /*----------*/ KC_Z, KC_U, KC_I, KC_O, KC_P, 
            KC_A, LT(5,KC_S), LT(1,KC_D), LT(3,KC_F), KC_G, /*----------*/ KC_H, LT(4,KC_J), LT(2,KC_K), LT(6,KC_L), KC_DOT, 
            KC_Y, KC_X, LALT_T(KC_C), KC_V, KC_B, /*----------*/ KC_N, KC_M, LALT_T(KC_NO), KC_NO, LT(7,KC_NO), 
            KC_LSFT, KC_SPC, /*----------*/ KC_RCTL, KC_RGUI),

	[1] = LAYOUT_split_3x5_2(

            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_P, /*----------*/ KC_BTN3, KC_TRNS, KC_WH_U, KC_TRNS, KC_TRNS, 
            KC_TRNS, KC_BTN2, KC_NO, KC_BTN1, KC_TRNS, /*----------*/ KC_BTN1, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, 
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, /*----------*/ KC_BTN2, KC_WH_L, KC_WH_D, KC_WH_R, KC_TRNS, 
            KC_TRNS, KC_TRNS, /*----------*/ KC_TRNS, KC_LGUI),

	[2] = LAYOUT_split_3x5_2(

            KC_TRNS, KC_TRNS, KC_PGUP, KC_TRNS, KC_P, /*----------*/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BSPC, 
            KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_U, /*----------*/ KC_TRNS, KC_LGUI, KC_NO, LCTL(KC_LALT), LCA(KC_LSFT), 
            KC_TRNS, KC_HOME, KC_PGDN, KC_END, KC_K, /*----------*/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
            KC_TRNS, KC_DEL, /*----------*/  KC_SPC, KC_LGUI),

	[3] = LAYOUT_split_3x5_2(

            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, /*----------*/ KC_TRNS, KC_UNDS, KC_PIPE, KC_QUOT, KC_BSPC, 
            KC_CIRC, KC_ASTR, KC_AMPR, KC_NO, KC_TRNS, /*----------*/ KC_HASH, KC_TILD, KC_SLSH, KC_DQUO, KC_DLR,
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, /*----------*/ KC_TRNS, KC_MINS, KC_NUBS, KC_GRV, KC_TRNS, 
            KC_TRNS, KC_TRNS, /*----------*/ KC_LEAD, KC_LGUI),

	[4] = LAYOUT_split_3x5_2(

            KC_TRNS, KC_COLN, KC_LT, KC_GT, KC_SCLN, /*----------*/ KC_TRNS, KC_TRNS, KC_DOT, KC_COMM, KC_MINS, 
            KC_LCBR, KC_RCBR, KC_LPRN, KC_RPRN, KC_AT, /*----------*/ KC_TRNS, KC_TRNS, KC_EQL, KC_PLUS, KC_SCLN, 
            KC_TRNS, KC_EXLM, KC_LBRC, KC_RBRC, KC_TRNS, /*----------*/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
            KC_TRNS, KC_TRNS, /*----------*/ KC_TRNS, KC_LGUI),

	[5] = LAYOUT_split_3x5_2(

            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, /*----------*/ KC_1, KC_F7, KC_F8, KC_F9, KC_F10, 
            KC_TRNS, KC_NO, LCTL(KC_LALT), KC_TRNS, KC_TRNS, /*----------*/ KC_TRNS, KC_F4, KC_F5, KC_F6, KC_F11, 
            KC_TRNS, KC_A, KC_TRNS, KC_TRNS, KC_TRNS, /*----------*/ KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F12, 
            KC_TRNS, KC_V, /*----------*/ KC_TRNS, KC_LGUI),

	[6] = LAYOUT_split_3x5_2(

            KC_COMM, KC_7, KC_8, KC_9, KC_PLUS, /*----------*/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
            KC_0, KC_1, KC_2, KC_3, KC_MINS, /*----------*/ KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_TRNS, 
            KC_DOT, KC_4, KC_5, KC_6, KC_PSLS, /*----------*/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, 
            KC_TRNS, KC_ASTR, /*----------*/ KC_TRNS, KC_LGUI),

	[7] = LAYOUT_split_3x5_2(

            RALT(KC_P), KC_TRNS, KC_COLN, KC_ESC, KC_TRNS, /*----------*/ KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_DEL, 
            RALT(KC_Q), KC_PERC, KC_SLSH, KC_ENT, KC_TRNS, /*----------*/ KC_TRNS, KC_NO, KC_TRNS, KC_TRNS, QK_BOOT, 
            RALT(KC_Y), RALT(KC_S), KC_TRNS, KC_EXLM, KC_INS, /*----------*/ KC_COMM, KC_DOT, RALT(KC_COMM), KC_NO, KC_NO, 
            KC_BSPC, KC_TAB, /*----------*/ KC_TRNS, KC_RGUI)

};


