#include QMK_KEYBOARD_H
/* #include "3_5_2_layout.h" */
#include "cl4rknova.h"

#define LAYOUT_wrapper(...) LAYOUT_planck_1x2uC(__VA_ARGS__)
/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

LEADER_EXTERNS();
void matrix_scan_user(void) {
  LEADER_DICTIONARY() {
    leading = false;
    leader_end();
    // Replace the sequences below with your own sequences.
    SEQ_ONE_KEY(KC_T) {
      // When I press KC_LEAD and then T, this sends CTRL + SHIFT + T
      SEND_STRING(SS_LCTRL(SS_LSFT("t")));
    }
    // Note: This is not an array, you don't need to put any commas
    // or semicolons between sequences.
    SEQ_TWO_KEYS(KC_N, KC_T) {
      // When I press KC_LEAD and then N followed by T, this sends CTRL + T
      SEND_STRING(SS_LCTRL("t"));
    }
  }
}

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer0_row1_left, _______, _______, _______cl4rkn0v4_layer0_row1_right,
          _______cl4rkn0v4_layer0_row2_left, _______, _______, _______cl4rkn0v4_layer0_row2_right,
          _______cl4rkn0v4_layer0_row3_left, _______, _______, _______cl4rkn0v4_layer0_row3_right,
          _______, _______,  _______, _______cl4rkn0v4_layer0_row4_left, _______,  _______cl4rkn0v4_layer0_row4_right, _______, _______,  _______
          ),
	[1] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer1_row1_left,  _______,    _______, _______cl4rkn0v4_layer1_row1_right, 
          _______cl4rkn0v4_layer1_row2_left,  _______,    _______, _______cl4rkn0v4_layer1_row2_right, 
          _______cl4rkn0v4_layer1_row3_left,  _______,    _______, _______cl4rkn0v4_layer1_row3_right, 
          _______, _______,  _______, _______cl4rkn0v4_layer1_row4_left,  _______,  _______cl4rkn0v4_layer1_row4_right, _______, _______,  _______

            
            ),
    [2] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer2_row1_left,  _______,    _______, _______cl4rkn0v4_layer2_row1_right, 
          _______cl4rkn0v4_layer2_row2_left,  _______,    _______, _______cl4rkn0v4_layer2_row2_right, 
          _______cl4rkn0v4_layer2_row3_left,  _______,    _______, _______cl4rkn0v4_layer2_row3_right, 
          _______, _______,  _______, _______cl4rkn0v4_layer2_row4_left,  _______,  _______cl4rkn0v4_layer2_row4_right, _______, _______,  _______

           
            ),
    [3] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer3_row1_left,  _______,    _______, _______cl4rkn0v4_layer3_row1_right, 
          _______cl4rkn0v4_layer3_row2_left,  _______,    _______, _______cl4rkn0v4_layer3_row2_right, 
          _______cl4rkn0v4_layer3_row3_left,  _______,    _______, _______cl4rkn0v4_layer3_row3_right, 
          _______, _______,  _______, _______cl4rkn0v4_layer3_row4_left,  _______,  _______cl4rkn0v4_layer3_row4_right, _______, _______,  _______

          
            ),
    [4] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer4_row1_left,  _______,    _______, _______cl4rkn0v4_layer4_row1_right, 
          _______cl4rkn0v4_layer4_row2_left,  _______,    _______, _______cl4rkn0v4_layer4_row2_right, 
          _______cl4rkn0v4_layer4_row3_left,  _______,    _______, _______cl4rkn0v4_layer4_row3_right, 
          _______, _______,  _______, _______cl4rkn0v4_layer4_row4_left,  _______,  _______cl4rkn0v4_layer4_row4_right, _______, _______,  _______
        
            ),
    [5] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer5_row1_left,  _______,    _______, _______cl4rkn0v4_layer5_row1_right, 
          _______cl4rkn0v4_layer5_row2_left,  _______,    _______, _______cl4rkn0v4_layer5_row2_right, 
          _______cl4rkn0v4_layer5_row3_left,  _______,    _______, _______cl4rkn0v4_layer5_row3_right, 
          _______, _______,  _______, _______cl4rkn0v4_layer5_row4_left,  _______,  _______cl4rkn0v4_layer5_row4_right, _______, _______,  _______
      
            ),
    [6] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer6_row1_left,  _______,    _______, _______cl4rkn0v4_layer6_row1_right, 
          _______cl4rkn0v4_layer6_row2_left,  _______,    _______, _______cl4rkn0v4_layer6_row2_right, 
          _______cl4rkn0v4_layer6_row3_left,  _______,    _______, _______cl4rkn0v4_layer6_row3_right, 
          _______, _______,  _______, _______cl4rkn0v4_layer6_row4_left,  _______, _______cl4rkn0v4_layer6_row4_right, _______, _______,  _______
    
            ),
    [7] = LAYOUT_wrapper(

          _______cl4rkn0v4_layer7_row1_left,  _______,    _______, _______cl4rkn0v4_layer7_row1_right, 
          _______cl4rkn0v4_layer7_row2_left,  _______,    _______, _______cl4rkn0v4_layer7_row2_right, 
          _______cl4rkn0v4_layer7_row3_left,  _______,    _______, _______cl4rkn0v4_layer7_row3_right, 
          _______, _______,  _______, _______cl4rkn0v4_layer7_row4_left,  _______, _______cl4rkn0v4_layer7_row4_right, _______, _______,  _______
  
            )};


