/*
 * cl4rknova.h
 * Copyright (C) 2022 mseibert <mseibert@LXKA-5KSJRG3.united.domain>
 *
 * Distributed under terms of the MIT license.
 */

#pragma once
#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

# define _______cl4rkn0v4_layer0_row1_left      KC_Q,          KC_W,            KC_E,           KC_R,          KC_T
# define _______cl4rkn0v4_layer0_row2_left      KC_A,          LT(5,KC_S),      LT(1,KC_D),     LT(3,KC_F),    KC_G
# define _______cl4rkn0v4_layer0_row3_left      KC_Y,          KC_X,            LALT_T(KC_C),   KC_V, KC_B
# define _______cl4rkn0v4_layer0_row4_left      KC_SPC,        KC_LSFT

# define _______cl4rkn0v4_layer1_row1_left      KC_TRNS,       KC_TRNS,         KC_TRNS,        KC_TRNS,       KC_P
# define _______cl4rkn0v4_layer1_row2_left      KC_TRNS,       KC_BTN2,         KC_TRNS,        KC_BTN1,       KC_TRNS
# define _______cl4rkn0v4_layer1_row3_left      KC_TRNS,       KC_TRNS,         KC_TRNS,        KC_TRNS,       KC_TRNS
# define _______cl4rkn0v4_layer1_row4_left      KC_TRNS,       KC_TRNS  

# define _______cl4rkn0v4_layer2_row1_left      KC_TRNS,       KC_TRNS,         KC_PGUP,        KC_TRNS,        KC_P
# define _______cl4rkn0v4_layer2_row2_left      KC_LEFT,       KC_UP,           KC_DOWN,        KC_RGHT,        KC_U
# define _______cl4rkn0v4_layer2_row3_left      KC_TRNS,       KC_HOME,         KC_PGDN,        KC_END,         KC_K
# define _______cl4rkn0v4_layer2_row4_left      KC_TRNS,        KC_DEL  

# define _______cl4rkn0v4_layer3_row1_left      KC_TRNS,       KC_TRNS,         KC_TRNS,        KC_TRNS,        KC_TRNS
# define _______cl4rkn0v4_layer3_row2_left      KC_CIRC,       KC_ASTR,         KC_AMPR,        KC_TRNS,        KC_TRNS
# define _______cl4rkn0v4_layer3_row3_left      KC_TRNS,       KC_TRNS,         KC_TRNS,        KC_TRNS,        KC_TRNS
# define _______cl4rkn0v4_layer3_row4_left      KC_TRNS,        KC_TRNS 

# define _______cl4rkn0v4_layer4_row1_left      KC_TRNS,       KC_COLN,         KC_LT,          KC_GT,           KC_SCLN
# define _______cl4rkn0v4_layer4_row2_left      KC_LCBR,       KC_RCBR,         KC_LPRN,        KC_RPRN,         KC_AT
# define _______cl4rkn0v4_layer4_row3_left      KC_TRNS,       KC_EXLM,         KC_LBRC,        KC_RBRC,         KC_TRNS
# define _______cl4rkn0v4_layer4_row4_left      KC_TRNS,         KC_TRNS

# define _______cl4rkn0v4_layer5_row1_left      KC_TRNS,       KC_TRNS,         KC_TRNS,       KC_TRNS,     KC_TRNS
# define _______cl4rkn0v4_layer5_row2_left      KC_TRNS,       _______,         LCTL(KC_LALT), KC_TRNS,     KC_TRNS
# define _______cl4rkn0v4_layer5_row3_left      KC_TRNS,       KC_A,            KC_TRNS,       KC_TRNS,     KC_TRNS
# define _______cl4rkn0v4_layer5_row4_left      KC_TRNS,     KC_V

# define _______cl4rkn0v4_layer6_row1_left      KC_TRNS,       KC_7,           KC_8,          KC_9,        RGB_MOD
# define _______cl4rkn0v4_layer6_row2_left      KC_0,          KC_1,           KC_2,          KC_3,        KC_TRNS
# define _______cl4rkn0v4_layer6_row3_left      KC_TRNS,       KC_4,           KC_5,          KC_6,        KC_TRNS
# define _______cl4rkn0v4_layer6_row4_left      KC_TRNS,     KC_TRNS

# define _______cl4rkn0v4_layer7_row1_left      RALT(KC_P),    KC_TRNS,        KC_COLN,    KC_ESC,     KC_TRNS
# define _______cl4rkn0v4_layer7_row2_left      RALT(KC_Q),    KC_PERC,        KC_SLSH,    KC_ENT,     KC_TRNS
# define _______cl4rkn0v4_layer7_row3_left      RALT(KC_Y),    RALT(KC_S),     KC_TRNS,    KC_EXLM,    KC_INS
# define _______cl4rkn0v4_layer7_row4_left      KC_BSPC,    KC_TAB

/* #################### */

# define _______cl4rkn0v4_layer0_row1_right     KC_Z,       KC_U,             KC_I,             KC_O, KC_P
# define _______cl4rkn0v4_layer0_row2_right     KC_H,       LT(4,KC_J),       LT(2,KC_K),       LT(6,KC_L),       KC_DOT
# define _______cl4rkn0v4_layer0_row3_right     KC_N,       KC_M,             LALT_T(KC_NO),    KC_NO,            LT(7,KC_NO)
# define _______cl4rkn0v4_layer0_row4_right     KC_RCTL,    KC_LGUI

# define _______cl4rkn0v4_layer1_row1_right     KC_TRNS,    KC_BTN1,          KC_WH_U,    KC_BTN2,    KC_TRNS
# define _______cl4rkn0v4_layer1_row2_right     KC_TRNS,    KC_MS_L,          KC_MS_D,    KC_MS_U,    KC_MS_R
# define _______cl4rkn0v4_layer1_row3_right     KC_TRNS,    KC_WH_L,          KC_WH_D,    KC_WH_R,    KC_TRNS
# define _______cl4rkn0v4_layer1_row4_right     KC_TRNS,    KC_TRNS

# define _______cl4rkn0v4_layer2_row1_right     KC_TRNS,    KC_C,             KC_R,       KC_L,          KC_BSPC
# define _______cl4rkn0v4_layer2_row2_right     KC_H,       KC_LGUI,          KC_N,       LCTL(KC_LALT), LCA(KC_LSFT)
# define _______cl4rkn0v4_layer2_row3_right     KC_TRNS,    KC_TRNS,          KC_TRNS,    KC_TRNS,       KC_TRNS
# define _______cl4rkn0v4_layer2_row4_right     KC_SPC,     KC_TRNS

# define _______cl4rkn0v4_layer3_row1_right     KC_TRNS,    KC_UNDS,          KC_PIPE,    KC_QUOT,       KC_BSPC
# define _______cl4rkn0v4_layer3_row2_right     KC_HASH,    KC_TILD,          KC_SLSH,    KC_DQUO,       KC_DLR
# define _______cl4rkn0v4_layer3_row3_right     KC_TRNS,    KC_MINS,          KC_NUBS,    KC_GRV,        KC_TRNS
# define _______cl4rkn0v4_layer3_row4_right     KC_TRNS,    KC_TRNS

# define _______cl4rkn0v4_layer4_row1_right     KC_TRNS,    KC_TRNS,          KC_DOT,      KC_COMM,      KC_MINS
# define _______cl4rkn0v4_layer4_row2_right     KC_TRNS,    KC_TRNS,          KC_EQL,    KC_PLUS,      KC_SCLN
# define _______cl4rkn0v4_layer4_row3_right     KC_TRNS,    KC_TRNS,          KC_TRNS,     KC_TRNS,      KC_TRNS
# define _______cl4rkn0v4_layer4_row4_right     KC_TRNS,    KC_TRNS

# define _______cl4rkn0v4_layer5_row1_right     KC_1,        KC_F7,           KC_F8,        KC_F9,      KC_F10
# define _______cl4rkn0v4_layer5_row2_right     KC_TRNS,     KC_F4,           KC_F5,        KC_F6,      KC_F11
# define _______cl4rkn0v4_layer5_row3_right     KC_TRNS,     KC_F1,           KC_F2,        KC_F3,      KC_F12
# define _______cl4rkn0v4_layer5_row4_right     KC_TRNS,     KC_TRNS

# define _______cl4rkn0v4_layer6_row1_right     KC_TRNS,     KC_TRNS,         KC_TRNS,    KC_TRNS,   KC_TRNS
# define _______cl4rkn0v4_layer6_row2_right     KC_TRNS,     KC_TRNS,         KC_TRNS,    _______,     KC_TRNS
# define _______cl4rkn0v4_layer6_row3_right     KC_TRNS,     KC_TRNS,         KC_TRNS,    KC_TRNS,   KC_TRNS
# define _______cl4rkn0v4_layer6_row4_right     KC_TRNS,     KC_TRNS

# define _______cl4rkn0v4_layer7_row1_right     KC_TRNS,     KC_TRNS,         KC_TRNS,       KC_TRNS,        KC_DEL
# define _______cl4rkn0v4_layer7_row2_right     KC_TRNS,     KC_LGUI,         KC_TRNS,       KC_TRNS,        QK_BOOT
# define _______cl4rkn0v4_layer7_row3_right     KC_COMM,     KC_DOT,          RALT(KC_COMM), RCTL_T(KC_DOT), _______
# define _______cl4rkn0v4_layer7_row4_right     KC_TRNS,     KC_TRNS
